// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tfkK31yQd93sN0MBysGyUfx-ywS8Gcc',
    appId: '1:170623020021:web:05b7607f3510d59c524ebc',
    messagingSenderId: '170623020021',
    projectId: 'weekly-menu-firebase-1',
    authDomain: 'weekly-menu-firebase-1.firebaseapp.com',
    databaseURL: 'https://weekly-menu-firebase-1.firebaseio.com',
    storageBucket: 'weekly-menu-firebase-1.appspot.com',
    measurementId: 'G-XDCL14E324',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuamhd7BXtkveDfymuy71tInuJd_lyVxc',
    appId: '1:170623020021:android:815776d810f79a6a524ebc',
    messagingSenderId: '170623020021',
    projectId: 'weekly-menu-firebase-1',
    databaseURL: 'https://weekly-menu-firebase-1.firebaseio.com',
    storageBucket: 'weekly-menu-firebase-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4gjgA--actCPpP3PLyUvIYnULq55YSg',
    appId: '1:170623020021:ios:c00a64d7cc4741d8524ebc',
    messagingSenderId: '170623020021',
    projectId: 'weekly-menu-firebase-1',
    databaseURL: 'https://weekly-menu-firebase-1.firebaseio.com',
    storageBucket: 'weekly-menu-firebase-1.appspot.com',
    iosClientId: '170623020021-k53drb44bcqggphss1nipdq73iofcbmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.weeklyMenuApp',
  );
}
