name: weekly_menu_workspace

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test
  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.
  clean:
    run: melos exec -c 1 --flutter -- "flutter clean"
    description: Clean all projects
  install:
    run: melos exec -c 1 --flutter -- "flutter pub get"
    description: Clean all projects
  build:android:release:
    run: cd apps/weekly_menu_app/ && flutter build apk --release
    description: Build release Android version
  build:web:release:
    run: cd apps/weekly_menu_app/ && flutter build web --profile
    description: Build release Web version
