# This workflows will upload a Python Package using Twine when a release is created.
# The package will include a stable version of the actionpi-ui that will be built here in this workflow.

name: Web - develop

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build web --profile #--web-renderer html --release
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          server-dir: ${{ secrets.FTP_REMOTE_FOLDER }}
          local-dir: ./build/web/
